TEST_PROGS = kunit.sh damo_tests.sh
TEST_PROGS += masim-record.sh masim-damos.sh chk_records.sh
TEST_PROGS += build_i386.sh build_m68k.sh build_arm64.sh
TEST_PROGS += build_i386_idle_flag.sh
TEST_PROGS += build_i386_highpte.sh

include ../lib.mk
