TEST_PROGS = kunit.sh
TEST_PROGS += huge_count_read_write.sh
TEST_PROGS += damo_tests.sh
TEST_PROGS += masim-record.sh masim-damos.sh chk_records.sh
TEST_PROGS += build_i386.sh build_m68k.sh build_arm64.sh
TEST_PROGS += build_i386_idle_flag.sh
TEST_PROGS += build_i386_highpte.sh

TEST_GEN_FILES += huge_count_read_write

include ../lib.mk
